# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'overview.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import QMessageBox

from queries2 import connection

class Ui_MainWindow(object):
    id_relatorio = 0
    tipoUser = 3
    user = ""

    # Determina o que cada tipo de usuário pode visualizar
    def checkPermissoes(self):
        if self.tipoUser == 1:
            self.widget.close()
            self.actionR1.setEnabled(False)
            self.actionR2.setEnabled(False)
            self.actionR3.setEnabled(False)
            self.actionR4.setEnabled(False)
            self.actionR5.setEnabled(True)   #
            self.actionR6.setEnabled(True)   #
            self.actionR7.setEnabled(False)
            self.menuSim.setEnabled(False)
            self.menuOverview.setEnabled(False)


        elif self.tipoUser == 2:
            self.widget.close()
            self.actionR1.setEnabled(False)
            self.actionR2.setEnabled(False)
            self.actionR3.setEnabled(False)
            self.actionR4.setEnabled(False)
            self.actionR5.setEnabled(True)   #
            self.actionR6.setEnabled(True)   #
            self.actionR7.setEnabled(False)
            self.menuSim.setEnabled(True)    #
            self.menuOverview.setEnabled(False)

        elif self.tipoUser == 3:
            # Tem acesso a tudo
            self.actionR1.setEnabled(True)
            self.actionR2.setEnabled(True)
            self.actionR3.setEnabled(True)
            self.actionR4.setEnabled(True)
            self.actionR5.setEnabled(True)
            self.actionR6.setEnabled(True)
            self.actionR7.setEnabled(True)
            self.menuSim.setEnabled(True)
            self.menuOverview.setEnabled(True)

    # Define o que cada botão da interface executa
    def selClick(self):
        op = self.id_relatorio

        if op == 1:
            self.click_actionR1(self.pesquisar)
        elif op == 2:
            self.click_actionR2(self.pesquisar)
        elif op == 3:
            self.click_actionR3(self.pesquisar)
        elif op == 4:
            self.click_actionR4(self.pesquisar)
        elif op == 5:
            self.click_actionR5(self.pesquisar)
        elif op == 6:
            self.click_actionR6(self.pesquisar)
        elif op == 7:
            self.click_actionR7(self.pesquisar)

    # Realiza a conexão entre os signals e slots da interface
    def settriggers(self):
        exibe_overview()

        self.actionR1.triggered.connect(self.click_actionR1)
        self.actionR2.triggered.connect(self.click_actionR2)
        self.actionR3.triggered.connect(self.click_actionR3)
        self.actionR4.triggered.connect(self.click_actionR4)
        self.actionR5.triggered.connect(self.click_actionR5)
        self.actionR6.triggered.connect(self.click_actionR6)
        self.actionR7.triggered.connect(self.click_actionR7)

        self.actionS1.triggered.connect(self.click_actionS1)
        self.actionS2.triggered.connect(self.click_actionS2)
        self.actionS3.triggered.connect(self.click_actionS3)

        self.S1_alterar_valor.clicked.connect(self.click_S1_alterar_valor)

        self.actionVisualizar.triggered.connect(self.click_overview)

        self.in_1_data.dateChanged.connect(self.atualiza_1)
        self.in_2_data.dateChanged.connect(self.atualiza_2)
        self.in_4_data.dateChanged.connect(self.atualiza_4)
        self.in_7_data.dateChanged.connect(self.atualiza_7)
        self.in_8_data_1.dateChanged.connect(self.atualiza_8)
        self.in_8_data_2.dateChanged.connect(self.atualiza_8)


        self.pesquisar.clicked.connect(self.selClick)

        self.lb_nomeuser.setText(self.user)
        self.lb_tipouser.setText(str(self.tipoUser))

        #preencher dado standard
        self.in_pesquisa.setText("Pesquisar")



    # ###################################################################### CLICK

    # Standard para criação de relatório
    def criaRelatorio(self, id, titulo, consulta, tabledata, header):
        self.id_relatorio = id

        self.widget.close()
        self.widget_relatorio.show()
        self.widget_relatorio_normal.show()
        self.widget_relatorio_P3.close()

        self.lb_titulo.setText(titulo)
        self.lb_consulta.setText(consulta)

        # Criação da tabela de relatorio generica
        tablemodel = MyTableModel(tabledata, header, self)
        self.tb_relatorio.setModel(tablemodel)
        vh = self.tb_relatorio.verticalHeader()
        vh.setVisible(False)
        hh = self.tb_relatorio.horizontalHeader()
        hh.setStretchLastSection(True)
        self.tb_relatorio.resizeColumnsToContents()
        self.tb_relatorio.resizeRowsToContents()


    # botao de ação de relatorio
    def click_actionR1(self, MainWindow):
        tabledata = connection.rel_1(self.in_pesquisa.text())
        header = ['NOME', 'E-MAIL', 'DATA DA VENDA', 'TIPO DE CARTÃO', 'NÚMERO DO CARTÃO', 'MÊS DA VALIDADE DO CARTÃO', 'ANO DA VALIDADE DO CARTÃO']
        self.criaRelatorio(1, "Clientes com Cartões Vencidos", "por nome", tabledata, header)

    def click_actionR2(self, MainWindow):
        tabledata = connection.rel_2(self.in_pesquisa.text())
        header = ['NOME', 'DEPARTAMENTO', 'TURNO', 'DATA DE ENTRADA', 'DATA DE SAÍDA']
        self.criaRelatorio(2, "Histórico de Departamento de Funcionários", "por nome", tabledata, header)

    def click_actionR3(self, MainWindow):
        self.widget.close()
        self.widget_relatorio.show()
        self.widget_relatorio_normal.close()
        self.widget_relatorio_P3.show()
        id_relatorio = 3
        self.lb_titulo.setText("Dados de frete")
        self.lb_consulta.setText("por ano (yyyy)")

        ano = self.in_pesquisa.text()


        tabledata1 = connection.rel_3_1(ano)
        header1 = ['SOMA TOTAL DOS FRETES', 'ANO']
        tablemodel1 = MyTableModel(tabledata1, header1, self)
        self.tb_relatorio_P3_1.setModel(tablemodel1)
        vh1 = self.tb_relatorio_P3_1.verticalHeader()
        vh1.setVisible(False)
        hh1 = self.tb_relatorio_P3_1.horizontalHeader()
        hh1.setStretchLastSection(True)
        self.tb_relatorio_P3_1.resizeColumnsToContents()
        self.tb_relatorio_P3_1.resizeRowsToContents()

        tabledata2 = connection.rel_3_2(ano)
        header2 = ['> 2000um', 'ANO']
        tablemodel2 = MyTableModel(tabledata2, header2, self)
        self.tb_relatorio_P3_2.setModel(tablemodel2)
        vh2 = self.tb_relatorio_P3_2.verticalHeader()
        vh2.setVisible(False)
        hh2 = self.tb_relatorio_P3_2.horizontalHeader()
        hh2.setStretchLastSection(True)
        self.tb_relatorio_P3_2.resizeColumnsToContents()
        self.tb_relatorio_P3_2.resizeRowsToContents()

        tabledata3 = connection.rel_3_3(ano)
        header3 = ['<= 2000um', 'ANO']
        tablemodel3 = MyTableModel(tabledata3, header3, self)
        self.tb_relatorio_P3_3.setModel(tablemodel3)
        vh3 = self.tb_relatorio_P3_3.verticalHeader()
        vh3.setVisible(False)
        hh3 = self.tb_relatorio_P3_3.horizontalHeader()
        hh3.setStretchLastSection(True)
        self.tb_relatorio_P3_3.resizeColumnsToContents()
        self.tb_relatorio_P3_3.resizeRowsToContents()

    def click_actionR4(self, MainWindow):
        tabledata = connection.rel_4(self.in_pesquisa.text())
        header = ['MÊS', 'TOTAL VENDIDO']
        self.criaRelatorio(4, "Informações das vendas anuais", "por ano (yyyy)", tabledata, header)

    def click_actionR5(self, MainWindow):
        tabledata = connection.rel_5(self.in_pesquisa.text())
        header = ['NOME', 'PREÇO', 'PESO', 'CATEGORIA', 'QUANTIDADE']
        self.criaRelatorio(5, "Top 15 produtos vendidos no semestre", "por data (DD/MM/yyyy)", tabledata, header)

    def click_actionR6(self, MainWindow):
        tabledata = connection.rel_6(self.in_pesquisa.text())
        header = ['A-CATEGORIA', 'A-SUBCATEGORIA', 'A-PRODUTO', 'A-QUANTIDADE', 'B-CATEGORIA', 'B-SUBCATEGORIA', 'B-PRODUTO', 'B-QUANTIDADE', 'TOTAL DOS DOIS JUNTOS']
        self.criaRelatorio(6, "Produtos de vendas casadas", "por quantidade",  tabledata, header)

    def click_actionR7(self, MainWindow):
        tabledata = connection.rel_7(self.in_pesquisa.text())
        header = ['TOTAL VENDIDO', 'PAÍS', ]
        self.criaRelatorio(7, "Vendas por país", "por país", tabledata, header)


    # botao de ação de simulação
    def click_actionS1(self, MainWindow):
        self.widgetS1.show()

        self.widgetS2.close()
        self.widgetS3.close()
        self.widget.close()
        self.widget_relatorio.close()

    def click_S1_alterar_valor(self):
        if(S1_valor(self.in_S1_idproduto.text(), self.in_S1_novovalor.text())):
            QMessageBox.about(self, "Simulação", "Dados alterados com sucesso!")
        else:
            QMessageBox.about(self, "Simulação", "Dados não alterados.")

    def click_actionS2(self, MainWindow):
        self.widgetS2.show()

        self.widgetS1.close()
        self.widgetS3.close()
        self.widget.close()
        self.widget_relatorio.close()

    def click_actionS3(self, MainWindow):
        self.widgetS3.show()

        self.widgetS1.close()
        self.widgetS2.close()
        self.widget.close()
        self.widget_relatorio.close()



    # botao de ação de overview
    def click_overview(self, MainWindow):
        exibe_overview()


    def exibe_overview():
        self.widget.show()

        self.widget_relatorio.close()
        self.widgetS1.show()
        self.widgetS2.close()
        self.widgetS3.close()



    # ###################################################################### OVERVIEW
    def populaOverview(self):
        self.atualiza_1()
        self.atualiza_2()
        self.atualiza_3()
        self.atualiza_4()
        self.atualiza_5()
        self.atualiza_6()
        self.atualiza_7()
        self.atualiza_8()

    # total vendido no dia, mes e ano
    def atualiza_1(self):
        #to-do passar separado os parametros para pesquisa
        data = self.in_1_data.text()
        array = connection.atualiza_1(data[0]+data[1], data[3]+data[4], data[6]+data[7]+data[8]+data[9])

        self.lb_1_dia.setText(str(array[0]))
        self.lb_1_mes.setText(str(array[1]))
        self.lb_1_ano.setText(str(array[2]))

    # top 3 funcionarios do mês e ano
    def atualiza_2(self):
        data = self.in_2_data.text()
        array = connection.atualiza_2(data[0]+data[1], data[3]+data[4]+data[5]+data[6])

        self.lb_2_a1.setText(str(array[0]))
        self.lb_2_a2.setText(str(array[1]))
        self.lb_2_a3.setText(str(array[2]))
        self.lb_2_m1.setText(str(array[3]))
        self.lb_2_m2.setText(str(array[4]))
        self.lb_2_m3.setText(str(array[5]))

    # top 15 produtos mais vendidos
    def atualiza_3(self):
        tabledata = connection.atualiza_3()
        header = ['NOME', 'PREÇO', 'PESO', 'CATEGORIA', 'QUANTIDADE']

        tablemodel = MyTableModel(tabledata, header, self)
        self.tb_3.setModel(tablemodel)
        vh = self.tb_3.verticalHeader()
        vh.setVisible(False)
        hh = self.tb_3.horizontalHeader()
        hh.setStretchLastSection(True)
        self.tb_3.resizeColumnsToContents()
        self.tb_3.resizeRowsToContents()

    # Melhores clientes do ano
    def atualiza_4(self):
        data = self.in_4_data.text()
        tabledata = connection.atualiza_4(data[0]+data[1]+data[2]+data[3])
        header = ['CLIENTE', 'TOTAL GASTO']

        tablemodel = MyTableModel(tabledata, header, self)
        self.tb_4.setModel(tablemodel)
        vh = self.tb_4.verticalHeader()
        vh.setVisible(False)
        hh = self.tb_4.horizontalHeader()
        hh.setStretchLastSection(True)
        self.tb_4.resizeColumnsToContents()
        self.tb_4.resizeRowsToContents()

    # Melhores clientes Ever
    def atualiza_5(self):
        tabledata = connection.atualiza_5()
        header = ['CLIENTE', 'TOTAL GASTO']

        tablemodel = MyTableModel(tabledata, header, self)
        self.tb_5.setModel(tablemodel)
        vh = self.tb_5.verticalHeader()
        vh.setVisible(False)
        hh = self.tb_5.horizontalHeader()
        hh.setStretchLastSection(True)
        self.tb_5.resizeColumnsToContents()
        self.tb_5.resizeRowsToContents()

    # produtos acabando (estoque < 10)
    def atualiza_6(self):
        tabledata = connection.atualiza_6()
        header = ['PRODUTO', 'QUANTIDADE']

        tablemodel = MyTableModel(tabledata, header, self)
        self.tb_6.setModel(tablemodel)
        vh = self.tb_6.verticalHeader()
        vh.setVisible(False)
        hh = self.tb_6.horizontalHeader()
        hh.setStretchLastSection(True)
        self.tb_6.resizeColumnsToContents()
        self.tb_6.resizeRowsToContents()

    # Total vendido por mês de um ano
    def atualiza_7(self):
        data = self.in_7_data.text()

        tabledata = connection.atualiza_7(data[0]+data[1]+data[2]+data[3])
        header = ['MÊS', 'TOTAL VENDIDO']

        tablemodel = MyTableModel(tabledata, header, self)
        self.tb_7.setModel(tablemodel)
        vh = self.tb_7.verticalHeader()
        vh.setVisible(False)
        hh = self.tb_7.horizontalHeader()
        hh.setStretchLastSection(True)
        self.tb_7.resizeColumnsToContents()
        self.tb_7.resizeRowsToContents()

    # Total vendido por Ano
    def atualiza_8(self):
        data = self.in_8_data_1.text()
        data2 = self.in_8_data_2.text()

        tabledata = connection.atualiza_8(data[0]+data[1]+data[2]+data[3], data2[0]+data2[1]+data2[2]+data2[3])
        header = ['ANO', 'TOTAL VENDIDO']

        tablemodel = MyTableModel(tabledata, header, self)
        self.tb_8.setModel(tablemodel)
        vh = self.tb_8.verticalHeader()
        vh.setVisible(False)
        hh = self.tb_8.horizontalHeader()
        hh.setStretchLastSection(True)
        self.tb_8.resizeColumnsToContents()
        self.tb_8.resizeRowsToContents()

    

    # ###################################################################### CONSTRUÇÃO DA INTERFACE

    # Chama funções ao final da construçao da interface
    def chamaFuncoes(self):
        self.settriggers()
        self.checkPermissoes()
        self.populaOverview()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1339, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lb_nomeuser = QtWidgets.QLabel(self.centralwidget)
        self.lb_nomeuser.setGeometry(QtCore.QRect(160, 10, 861, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.lb_nomeuser.setFont(font)
        self.lb_nomeuser.setObjectName("lb_nomeuser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lb_tipouser = QtWidgets.QLabel(self.centralwidget)
        self.lb_tipouser.setGeometry(QtCore.QRect(50, 10, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.lb_tipouser.setFont(font)
        self.lb_tipouser.setObjectName("lb_tipouser")
        self.widget_relatorio = QtWidgets.QWidget(self.centralwidget)
        self.widget_relatorio.setEnabled(True)
        self.widget_relatorio.setGeometry(QtCore.QRect(20, 30, 981, 491))
        self.widget_relatorio.setObjectName("widget_relatorio")
        self.in_pesquisa = QtWidgets.QLineEdit(self.widget_relatorio)
        self.in_pesquisa.setGeometry(QtCore.QRect(20, 50, 181, 20))
        self.in_pesquisa.setObjectName("in_pesquisa")
        self.pesquisar = QtWidgets.QPushButton(self.widget_relatorio)
        self.pesquisar.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.pesquisar.setObjectName("pesquisar")
        self.lb_titulo = QtWidgets.QLabel(self.widget_relatorio)
        self.lb_titulo.setGeometry(QtCore.QRect(20, 20, 681, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.lb_titulo.setFont(font)
        self.lb_titulo.setObjectName("lb_titulo")
        self.widget_relatorio_normal = QtWidgets.QWidget(self.widget_relatorio)
        self.widget_relatorio_normal.setGeometry(QtCore.QRect(10, 80, 811, 401))
        self.widget_relatorio_normal.setObjectName("widget_relatorio_normal")
        self.tb_relatorio = QtWidgets.QTableView(self.widget_relatorio_normal)
        self.tb_relatorio.setGeometry(QtCore.QRect(10, 10, 791, 381))
        self.tb_relatorio.setSortingEnabled(False)
        self.tb_relatorio.setObjectName("tb_relatorio")
        self.widget_relatorio_P3 = QtWidgets.QWidget(self.widget_relatorio)
        self.widget_relatorio_P3.setGeometry(QtCore.QRect(10, 70, 851, 411))
        self.widget_relatorio_P3.setObjectName("widget_relatorio_P3")
        self.tb_relatorio_P3_1 = QtWidgets.QTableView(self.widget_relatorio_P3)
        self.tb_relatorio_P3_1.setGeometry(QtCore.QRect(10, 20, 261, 381))
        self.tb_relatorio_P3_1.setSortingEnabled(False)
        self.tb_relatorio_P3_1.setObjectName("tb_relatorio_P3_1")
        self.tb_relatorio_P3_2 = QtWidgets.QTableView(self.widget_relatorio_P3)
        self.tb_relatorio_P3_2.setGeometry(QtCore.QRect(290, 20, 261, 381))
        self.tb_relatorio_P3_2.setSortingEnabled(False)
        self.tb_relatorio_P3_2.setObjectName("tb_relatorio_P3_2")
        self.tb_relatorio_P3_3 = QtWidgets.QTableView(self.widget_relatorio_P3)
        self.tb_relatorio_P3_3.setGeometry(QtCore.QRect(570, 20, 261, 381))
        self.tb_relatorio_P3_3.setSortingEnabled(False)
        self.tb_relatorio_P3_3.setObjectName("tb_relatorio_P3_3")
        self.lb_consulta = QtWidgets.QLabel(self.widget_relatorio)
        self.lb_consulta.setGeometry(QtCore.QRect(290, 50, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.lb_consulta.setFont(font)
        self.lb_consulta.setObjectName("lb_consulta")
        self.widget_S1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_S1.setGeometry(QtCore.QRect(20, 30, 541, 241))
        self.widget_S1.setObjectName("widget_S1")
        self.lb_titulo_1 = QtWidgets.QLabel(self.widget_S1)
        self.lb_titulo_1.setGeometry(QtCore.QRect(20, 20, 681, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.lb_titulo_1.setFont(font)
        self.lb_titulo_1.setObjectName("lb_titulo_1")
        self.in_S1_idproduto = QtWidgets.QLineEdit(self.widget_S1)
        self.in_S1_idproduto.setGeometry(QtCore.QRect(30, 110, 181, 20))
        self.in_S1_idproduto.setText("")
        self.in_S1_idproduto.setObjectName("in_S1_idproduto")
        self.lb_sim_a_1 = QtWidgets.QLabel(self.widget_S1)
        self.lb_sim_a_1.setGeometry(QtCore.QRect(30, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_sim_a_1.setFont(font)
        self.lb_sim_a_1.setObjectName("lb_sim_a_1")
        self.lb_sim_1 = QtWidgets.QLabel(self.widget_S1)
        self.lb_sim_1.setGeometry(QtCore.QRect(230, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_sim_1.setFont(font)
        self.lb_sim_1.setObjectName("lb_sim_1")
        self.in_S1_novovalor = QtWidgets.QLineEdit(self.widget_S1)
        self.in_S1_novovalor.setGeometry(QtCore.QRect(230, 110, 181, 20))
        self.in_S1_novovalor.setText("")
        self.in_S1_novovalor.setObjectName("in_S1_novovalor")
        self.S1_alterar_valor = QtWidgets.QPushButton(self.widget_S1)
        self.S1_alterar_valor.setGeometry(QtCore.QRect(430, 110, 75, 23))
        self.S1_alterar_valor.setObjectName("S1_alterar_valor")
        self.lb_sim_2 = QtWidgets.QLabel(self.widget_S1)
        self.lb_sim_2.setGeometry(QtCore.QRect(230, 160, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_sim_2.setFont(font)
        self.lb_sim_2.setObjectName("lb_sim_2")
        self.in_S1_novaquantidade = QtWidgets.QLineEdit(self.widget_S1)
        self.in_S1_novaquantidade.setGeometry(QtCore.QRect(230, 190, 181, 20))
        self.in_S1_novaquantidade.setText("")
        self.in_S1_novaquantidade.setObjectName("in_S1_novaquantidade")
        self.S1_alterar_quantidade = QtWidgets.QPushButton(self.widget_S1)
        self.S1_alterar_quantidade.setGeometry(QtCore.QRect(430, 190, 75, 23))
        self.S1_alterar_quantidade.setObjectName("S1_alterar_quantidade")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 40, 1261, 641))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(180, 60, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(290, 60, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.in_1_data = QtWidgets.QDateEdit(self.groupBox)
        self.in_1_data.setGeometry(QtCore.QRect(259, 20, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_1_data.setFont(font)
        self.in_1_data.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_1_data.setCalendarPopup(True)
        self.in_1_data.setObjectName("in_1_data")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(140, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lb_1_dia = QtWidgets.QLabel(self.groupBox)
        self.lb_1_dia.setGeometry(QtCore.QRect(20, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lb_1_dia.setFont(font)
        self.lb_1_dia.setObjectName("lb_1_dia")
        self.lb_1_mes = QtWidgets.QLabel(self.groupBox)
        self.lb_1_mes.setGeometry(QtCore.QRect(140, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lb_1_mes.setFont(font)
        self.lb_1_mes.setObjectName("lb_1_mes")
        self.lb_1_ano = QtWidgets.QLabel(self.groupBox)
        self.lb_1_ano.setGeometry(QtCore.QRect(270, 90, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lb_1_ano.setFont(font)
        self.lb_1_ano.setObjectName("lb_1_ano")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(250, 80, 16, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(120, 80, 16, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 381, 201))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(90, 60, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(260, 60, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.in_2_data = QtWidgets.QDateEdit(self.groupBox_2)
        self.in_2_data.setGeometry(QtCore.QRect(279, 20, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_2_data.setFont(font)
        self.in_2_data.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_2_data.setCalendarPopup(True)
        self.in_2_data.setObjectName("in_2_data")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(160, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lb_2_m1 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_2_m1.setGeometry(QtCore.QRect(20, 90, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lb_2_m1.setFont(font)
        self.lb_2_m1.setObjectName("lb_2_m1")
        self.lb_2_a1 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_2_a1.setGeometry(QtCore.QRect(200, 90, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lb_2_a1.setFont(font)
        self.lb_2_a1.setObjectName("lb_2_a1")
        self.lb_2_m2 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_2_m2.setGeometry(QtCore.QRect(20, 120, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lb_2_m2.setFont(font)
        self.lb_2_m2.setObjectName("lb_2_m2")
        self.lb_2_m3 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_2_m3.setGeometry(QtCore.QRect(20, 150, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lb_2_m3.setFont(font)
        self.lb_2_m3.setObjectName("lb_2_m3")
        self.lb_2_a2 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_2_a2.setGeometry(QtCore.QRect(200, 120, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lb_2_a2.setFont(font)
        self.lb_2_a2.setObjectName("lb_2_a2")
        self.lb_2_a3 = QtWidgets.QLabel(self.groupBox_2)
        self.lb_2_a3.setGeometry(QtCore.QRect(200, 150, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lb_2_a3.setFont(font)
        self.lb_2_a3.setObjectName("lb_2_a3")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(180, 60, 16, 131))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 350, 381, 281))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.tb_4 = QtWidgets.QTableView(self.groupBox_4)
        self.tb_4.setGeometry(QtCore.QRect(10, 50, 351, 221))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.tb_4.setFont(font)
        self.tb_4.setObjectName("tb_4")
        self.in_4_data = QtWidgets.QDateEdit(self.groupBox_4)
        self.in_4_data.setGeometry(QtCore.QRect(299, 20, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_4_data.setFont(font)
        self.in_4_data.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_4_data.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.in_4_data.setCalendarPopup(True)
        self.in_4_data.setObjectName("in_4_data")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(180, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_5.setGeometry(QtCore.QRect(400, 350, 381, 281))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.tb_5 = QtWidgets.QTableView(self.groupBox_5)
        self.tb_5.setGeometry(QtCore.QRect(10, 50, 361, 221))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.tb_5.setFont(font)
        self.tb_5.setObjectName("tb_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 10, 381, 331))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.tb_3 = QtWidgets.QTableView(self.groupBox_3)
        self.tb_3.setGeometry(QtCore.QRect(10, 21, 361, 301))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.tb_3.setFont(font)
        self.tb_3.setObjectName("tb_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_6.setGeometry(QtCore.QRect(790, 10, 461, 161))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.tb_6 = QtWidgets.QTableView(self.groupBox_6)
        self.tb_6.setGeometry(QtCore.QRect(10, 21, 441, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.tb_6.setFont(font)
        self.tb_6.setObjectName("tb_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setGeometry(QtCore.QRect(790, 180, 461, 221))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(270, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.in_7_data = QtWidgets.QDateEdit(self.groupBox_7)
        self.in_7_data.setGeometry(QtCore.QRect(389, 20, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_7_data.setFont(font)
        self.in_7_data.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_7_data.setCalendarPopup(True)
        self.in_7_data.setObjectName("in_7_data")
        self.tb_7 = QtWidgets.QTableView(self.groupBox_7)
        self.tb_7.setGeometry(QtCore.QRect(10, 50, 441, 161))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.tb_7.setFont(font)
        self.tb_7.setObjectName("tb_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_8.setGeometry(QtCore.QRect(790, 410, 461, 221))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.in_8_data_1 = QtWidgets.QDateEdit(self.groupBox_8)
        self.in_8_data_1.setGeometry(QtCore.QRect(220, 20, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_8_data_1.setFont(font)
        self.in_8_data_1.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_8_data_1.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.in_8_data_1.setCalendarPopup(True)
        self.in_8_data_1.setObjectName("in_8_data_1")
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(100, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.tb_8 = QtWidgets.QTableView(self.groupBox_8)
        self.tb_8.setGeometry(QtCore.QRect(10, 50, 441, 161))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.tb_8.setFont(font)
        self.tb_8.setObjectName("tb_8")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(290, 20, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.in_8_data_2 = QtWidgets.QDateEdit(self.groupBox_8)
        self.in_8_data_2.setGeometry(QtCore.QRect(330, 20, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_8_data_2.setFont(font)
        self.in_8_data_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_8_data_2.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.in_8_data_2.setCalendarPopup(True)
        self.in_8_data_2.setObjectName("in_8_data_2")
        self.widget_S2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_S2.setGeometry(QtCore.QRect(20, 30, 551, 241))
        self.widget_S2.setObjectName("widget_S2")
        self.lb_titulo_2 = QtWidgets.QLabel(self.widget_S2)
        self.lb_titulo_2.setGeometry(QtCore.QRect(20, 20, 681, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.lb_titulo_2.setFont(font)
        self.lb_titulo_2.setObjectName("lb_titulo_2")
        self.in_S2_idcategoria = QtWidgets.QLineEdit(self.widget_S2)
        self.in_S2_idcategoria.setGeometry(QtCore.QRect(30, 110, 181, 20))
        self.in_S2_idcategoria.setText("")
        self.in_S2_idcategoria.setObjectName("in_S2_idcategoria")
        self.lb_sim_a_2 = QtWidgets.QLabel(self.widget_S2)
        self.lb_sim_a_2.setGeometry(QtCore.QRect(30, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_sim_a_2.setFont(font)
        self.lb_sim_a_2.setObjectName("lb_sim_a_2")
        self.lb_sim_3 = QtWidgets.QLabel(self.widget_S2)
        self.lb_sim_3.setGeometry(QtCore.QRect(230, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_sim_3.setFont(font)
        self.lb_sim_3.setObjectName("lb_sim_3")
        self.in_S2_idsub = QtWidgets.QLineEdit(self.widget_S2)
        self.in_S2_idsub.setGeometry(QtCore.QRect(230, 110, 181, 20))
        self.in_S2_idsub.setText("")
        self.in_S2_idsub.setObjectName("in_S2_idsub")
        self.S2_alterar = QtWidgets.QPushButton(self.widget_S2)
        self.S2_alterar.setGeometry(QtCore.QRect(430, 110, 75, 23))
        self.S2_alterar.setObjectName("S2_alterar")
        self.widget_S3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_S3.setGeometry(QtCore.QRect(20, 30, 911, 711))
        self.widget_S3.setObjectName("widget_S3")
        self.lb_titulo_3 = QtWidgets.QLabel(self.widget_S3)
        self.lb_titulo_3.setGeometry(QtCore.QRect(20, 20, 681, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.lb_titulo_3.setFont(font)
        self.lb_titulo_3.setObjectName("lb_titulo_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget_S3)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 50, 661, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.lb_51 = QtWidgets.QLabel(self.groupBox_9)
        self.lb_51.setGeometry(QtCore.QRect(10, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_51.setFont(font)
        self.lb_51.setObjectName("lb_51")
        self.in_S2_1 = QtWidgets.QLineEdit(self.groupBox_9)
        self.in_S2_1.setGeometry(QtCore.QRect(10, 60, 181, 20))
        self.in_S2_1.setText("")
        self.in_S2_1.setObjectName("in_S2_1")
        self.S3_alterar_1 = QtWidgets.QPushButton(self.groupBox_9)
        self.S3_alterar_1.setGeometry(QtCore.QRect(210, 60, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.S3_alterar_1.setFont(font)
        self.S3_alterar_1.setObjectName("S3_alterar_1")
        self.groupBox_10 = QtWidgets.QGroupBox(self.widget_S3)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 180, 661, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.lb_53 = QtWidgets.QLabel(self.groupBox_10)
        self.lb_53.setGeometry(QtCore.QRect(10, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_53.setFont(font)
        self.lb_53.setObjectName("lb_53")
        self.S3_alterar_2 = QtWidgets.QPushButton(self.groupBox_10)
        self.S3_alterar_2.setGeometry(QtCore.QRect(370, 60, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.S3_alterar_2.setFont(font)
        self.S3_alterar_2.setObjectName("S3_alterar_2")
        self.in_S3_datainicial = QtWidgets.QDateEdit(self.groupBox_10)
        self.in_S3_datainicial.setGeometry(QtCore.QRect(10, 60, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_S3_datainicial.setFont(font)
        self.in_S3_datainicial.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_S3_datainicial.setCalendarPopup(True)
        self.in_S3_datainicial.setObjectName("in_S3_datainicial")
        self.lb_54 = QtWidgets.QLabel(self.groupBox_10)
        self.lb_54.setGeometry(QtCore.QRect(130, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_54.setFont(font)
        self.lb_54.setObjectName("lb_54")
        self.lb_55 = QtWidgets.QLabel(self.groupBox_10)
        self.lb_55.setGeometry(QtCore.QRect(250, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_55.setFont(font)
        self.lb_55.setObjectName("lb_55")
        self.in_S3_datafinal = QtWidgets.QDateEdit(self.groupBox_10)
        self.in_S3_datafinal.setGeometry(QtCore.QRect(130, 60, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_S3_datafinal.setFont(font)
        self.in_S3_datafinal.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_S3_datafinal.setCalendarPopup(True)
        self.in_S3_datafinal.setObjectName("in_S3_datafinal")
        self.in_S3_desconto = QtWidgets.QLineEdit(self.groupBox_10)
        self.in_S3_desconto.setGeometry(QtCore.QRect(250, 60, 101, 20))
        self.in_S3_desconto.setText("")
        self.in_S3_desconto.setObjectName("in_S3_desconto")
        self.groupBox_11 = QtWidgets.QGroupBox(self.widget_S3)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 310, 661, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.lb_56 = QtWidgets.QLabel(self.groupBox_11)
        self.lb_56.setGeometry(QtCore.QRect(10, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_56.setFont(font)
        self.lb_56.setObjectName("lb_56")
        self.S3_alterar_3 = QtWidgets.QPushButton(self.groupBox_11)
        self.S3_alterar_3.setGeometry(QtCore.QRect(540, 60, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.S3_alterar_3.setFont(font)
        self.S3_alterar_3.setObjectName("S3_alterar_3")
        self.in_S3_datainicial_3 = QtWidgets.QDateEdit(self.groupBox_11)
        self.in_S3_datainicial_3.setGeometry(QtCore.QRect(10, 60, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_S3_datainicial_3.setFont(font)
        self.in_S3_datainicial_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_S3_datainicial_3.setCalendarPopup(True)
        self.in_S3_datainicial_3.setObjectName("in_S3_datainicial_3")
        self.lb_57 = QtWidgets.QLabel(self.groupBox_11)
        self.lb_57.setGeometry(QtCore.QRect(130, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_57.setFont(font)
        self.lb_57.setObjectName("lb_57")
        self.lb_58 = QtWidgets.QLabel(self.groupBox_11)
        self.lb_58.setGeometry(QtCore.QRect(420, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_58.setFont(font)
        self.lb_58.setObjectName("lb_58")
        self.in_S3_datafinal_3 = QtWidgets.QDateEdit(self.groupBox_11)
        self.in_S3_datafinal_3.setGeometry(QtCore.QRect(130, 60, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.in_S3_datafinal_3.setFont(font)
        self.in_S3_datafinal_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 6, 21), QtCore.QTime(0, 0, 0)))
        self.in_S3_datafinal_3.setCalendarPopup(True)
        self.in_S3_datafinal_3.setObjectName("in_S3_datafinal_3")
        self.in_S3_desconto_3 = QtWidgets.QLineEdit(self.groupBox_11)
        self.in_S3_desconto_3.setGeometry(QtCore.QRect(420, 60, 101, 20))
        self.in_S3_desconto_3.setText("")
        self.in_S3_desconto_3.setObjectName("in_S3_desconto_3")
        self.lb_59 = QtWidgets.QLabel(self.groupBox_11)
        self.lb_59.setGeometry(QtCore.QRect(250, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_59.setFont(font)
        self.lb_59.setObjectName("lb_59")
        self.in_S3_valormin_3 = QtWidgets.QLineEdit(self.groupBox_11)
        self.in_S3_valormin_3.setGeometry(QtCore.QRect(250, 60, 121, 20))
        self.in_S3_valormin_3.setText("")
        self.in_S3_valormin_3.setObjectName("in_S3_valormin_3")
        self.groupBox_12 = QtWidgets.QGroupBox(self.widget_S3)
        self.groupBox_12.setGeometry(QtCore.QRect(20, 570, 661, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.S3_alterar_5 = QtWidgets.QPushButton(self.groupBox_12)
        self.S3_alterar_5.setGeometry(QtCore.QRect(210, 60, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.S3_alterar_5.setFont(font)
        self.S3_alterar_5.setObjectName("S3_alterar_5")
        self.lb_64 = QtWidgets.QLabel(self.groupBox_12)
        self.lb_64.setGeometry(QtCore.QRect(10, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_64.setFont(font)
        self.lb_64.setObjectName("lb_64")
        self.in_S2_3 = QtWidgets.QLineEdit(self.groupBox_12)
        self.in_S2_3.setGeometry(QtCore.QRect(10, 60, 181, 20))
        self.in_S2_3.setText("")
        self.in_S2_3.setObjectName("in_S2_3")
        self.groupBox_13 = QtWidgets.QGroupBox(self.widget_S3)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 440, 661, 121))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.S3_alterar__4 = QtWidgets.QPushButton(self.groupBox_13)
        self.S3_alterar__4.setGeometry(QtCore.QRect(270, 60, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.S3_alterar__4.setFont(font)
        self.S3_alterar__4.setObjectName("S3_alterar__4")
        self.lb_65 = QtWidgets.QLabel(self.groupBox_13)
        self.lb_65.setGeometry(QtCore.QRect(140, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_65.setFont(font)
        self.lb_65.setObjectName("lb_65")
        self.in_S3_descontopais = QtWidgets.QLineEdit(self.groupBox_13)
        self.in_S3_descontopais.setGeometry(QtCore.QRect(140, 60, 101, 20))
        self.in_S3_descontopais.setText("")
        self.in_S3_descontopais.setObjectName("in_S3_descontopais")
        self.in_S3_siglapais = QtWidgets.QLineEdit(self.groupBox_13)
        self.in_S3_siglapais.setGeometry(QtCore.QRect(10, 60, 101, 20))
        self.in_S3_siglapais.setText("")
        self.in_S3_siglapais.setObjectName("in_S3_siglapais")
        self.lb_66 = QtWidgets.QLabel(self.groupBox_13)
        self.lb_66.setGeometry(QtCore.QRect(10, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.lb_66.setFont(font)
        self.lb_66.setObjectName("lb_66")
        self.label.raise_()
        self.lb_nomeuser.raise_()
        self.label_3.raise_()
        self.lb_tipouser.raise_()
        self.widget_S1.raise_()
        self.widget.raise_()
        self.widget_relatorio.raise_()
        self.widget_S2.raise_()
        self.widget_S3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1339, 21))
        self.menubar.setObjectName("menubar")
        self.menuUser = QtWidgets.QMenu(self.menubar)
        self.menuUser.setObjectName("menuUser")
        self.menuSim = QtWidgets.QMenu(self.menubar)
        self.menuSim.setObjectName("menuSim")
        self.menuRel = QtWidgets.QMenu(self.menubar)
        self.menuRel.setObjectName("menuRel")
        self.menuOverview = QtWidgets.QMenu(self.menubar)
        self.menuOverview.setObjectName("menuOverview")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionR1 = QtWidgets.QAction(MainWindow)
        self.actionR1.setObjectName("actionR1")
        self.actionR2 = QtWidgets.QAction(MainWindow)
        self.actionR2.setObjectName("actionR2")
        self.actionR3 = QtWidgets.QAction(MainWindow)
        self.actionR3.setObjectName("actionR3")
        self.actionR4 = QtWidgets.QAction(MainWindow)
        self.actionR4.setObjectName("actionR4")
        self.actionR5 = QtWidgets.QAction(MainWindow)
        self.actionR5.setObjectName("actionR5")
        self.actionR6 = QtWidgets.QAction(MainWindow)
        self.actionR6.setObjectName("actionR6")
        self.actionR7 = QtWidgets.QAction(MainWindow)
        self.actionR7.setObjectName("actionR7")
        self.actionS1 = QtWidgets.QAction(MainWindow)
        self.actionS1.setObjectName("actionS1")
        self.actionS2 = QtWidgets.QAction(MainWindow)
        self.actionS2.setObjectName("actionS2")
        self.actionS3 = QtWidgets.QAction(MainWindow)
        self.actionS3.setObjectName("actionS3")
        self.actionCr_ditos = QtWidgets.QAction(MainWindow)
        self.actionCr_ditos.setObjectName("actionCr_ditos")
        self.actionOverview = QtWidgets.QAction(MainWindow)
        self.actionOverview.setObjectName("actionOverview")
        self.actionVisualizar = QtWidgets.QAction(MainWindow)
        self.actionVisualizar.setObjectName("actionVisualizar")
        self.menuUser.addAction(self.actionSair)
        self.menuUser.addSeparator()
        self.menuUser.addAction(self.actionCr_ditos)
        self.menuSim.addAction(self.actionS1)
        self.menuSim.addAction(self.actionS2)
        self.menuSim.addAction(self.actionS3)
        self.menuRel.addAction(self.actionR1)
        self.menuRel.addAction(self.actionR2)
        self.menuRel.addAction(self.actionR3)
        self.menuRel.addAction(self.actionR4)
        self.menuRel.addAction(self.actionR5)
        self.menuRel.addAction(self.actionR6)
        self.menuRel.addAction(self.actionR7)
        self.menuOverview.addAction(self.actionVisualizar)
        self.menubar.addAction(self.menuUser.menuAction())
        self.menubar.addAction(self.menuOverview.menuAction())
        self.menubar.addAction(self.menuRel.menuAction())
        self.menubar.addAction(self.menuSim.menuAction())
        self.lb_titulo.setBuddy(self.in_1_data)
        self.lb_consulta.setBuddy(self.in_1_data)
        self.lb_titulo_1.setBuddy(self.in_1_data)
        self.lb_sim_a_1.setBuddy(self.in_1_data)
        self.lb_sim_1.setBuddy(self.in_1_data)
        self.lb_sim_2.setBuddy(self.in_1_data)
        self.label_6.setBuddy(self.in_1_data)
        self.label_13.setBuddy(self.in_2_data)
        self.label_14.setBuddy(self.in_4_data)
        self.label_16.setBuddy(self.in_7_data)
        self.label_15.setBuddy(self.in_8_data_1)
        self.label_17.setBuddy(self.in_8_data_1)
        self.lb_titulo_2.setBuddy(self.in_1_data)
        self.lb_sim_a_2.setBuddy(self.in_1_data)
        self.lb_sim_3.setBuddy(self.in_1_data)
        self.lb_titulo_3.setBuddy(self.in_1_data)
        self.lb_51.setBuddy(self.in_1_data)
        self.lb_53.setBuddy(self.in_1_data)
        self.lb_54.setBuddy(self.in_1_data)
        self.lb_55.setBuddy(self.in_1_data)
        self.lb_56.setBuddy(self.in_1_data)
        self.lb_57.setBuddy(self.in_1_data)
        self.lb_58.setBuddy(self.in_1_data)
        self.lb_59.setBuddy(self.in_1_data)
        self.lb_64.setBuddy(self.in_1_data)
        self.lb_65.setBuddy(self.in_1_data)
        self.lb_66.setBuddy(self.in_1_data)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.in_1_data, self.in_2_data)
        MainWindow.setTabOrder(self.in_2_data, self.tb_3)
        MainWindow.setTabOrder(self.tb_3, self.in_4_data)
        MainWindow.setTabOrder(self.in_4_data, self.tb_4)
        MainWindow.setTabOrder(self.tb_4, self.tb_5)
        MainWindow.setTabOrder(self.tb_5, self.tb_6)
        MainWindow.setTabOrder(self.tb_6, self.in_7_data)
        MainWindow.setTabOrder(self.in_7_data, self.in_8_data_1)

        self.chamaFuncoes()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ABC System"))
        self.label.setText(_translate("MainWindow", "Usuário:"))
        self.lb_nomeuser.setText(_translate("MainWindow", "John Doe"))
        self.label_3.setText(_translate("MainWindow", "Tipo:"))
        self.lb_tipouser.setText(_translate("MainWindow", "3"))
        self.in_pesquisa.setText(_translate("MainWindow", "Pesquisar"))
        self.pesquisar.setText(_translate("MainWindow", "Pesquisar"))
        self.lb_titulo.setText(_translate("MainWindow", "Relatório Bla bla bla"))
        self.lb_consulta.setText(_translate("MainWindow", "filtro"))
        self.lb_titulo_1.setText(_translate("MainWindow", "Simulação - Alteração da Tabela Produto"))
        self.lb_sim_a_1.setText(_translate("MainWindow", "ID Produto"))
        self.lb_sim_1.setText(_translate("MainWindow", "Novo Valor"))
        self.S1_alterar_valor.setText(_translate("MainWindow", "Alterar"))
        self.lb_sim_2.setText(_translate("MainWindow", "Nova Quantidade"))
        self.S1_alterar_quantidade.setText(_translate("MainWindow", "Alterar"))
        self.groupBox.setTitle(_translate("MainWindow", "Total Vendido"))
        self.label_2.setText(_translate("MainWindow", "Dia"))
        self.label_4.setText(_translate("MainWindow", "Mês"))
        self.label_5.setText(_translate("MainWindow", "Ano"))
        self.label_6.setText(_translate("MainWindow", "Selecione o período:"))
        self.lb_1_dia.setText(_translate("MainWindow", "99999"))
        self.lb_1_mes.setText(_translate("MainWindow", "99999"))
        self.lb_1_ano.setText(_translate("MainWindow", "99999"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Top 3 Funcionários"))
        self.label_11.setText(_translate("MainWindow", "Mês"))
        self.label_12.setText(_translate("MainWindow", "Ano"))
        self.in_2_data.setDisplayFormat(_translate("MainWindow", "MM/yyyy"))
        self.label_13.setText(_translate("MainWindow", "Selecione o período:"))
        self.lb_2_m1.setText(_translate("MainWindow", "Jair"))
        self.lb_2_a1.setText(_translate("MainWindow", "Nair"))
        self.lb_2_m2.setText(_translate("MainWindow", "Jaer"))
        self.lb_2_m3.setText(_translate("MainWindow", "Jaur"))
        self.lb_2_a2.setText(_translate("MainWindow", "Neir"))
        self.lb_2_a3.setText(_translate("MainWindow", "Noir"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Melhores clientes do Ano"))
        self.in_4_data.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.label_14.setText(_translate("MainWindow", "Selecione o período:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Melhores clientes Ever"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Top 15 Produtos Mais Vendidos"))
        self.groupBox_6.setTitle(_translate("MainWindow", "!!! Produtos acabando !!!"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Total Vendido por Mês"))
        self.label_16.setText(_translate("MainWindow", "Selecione o período:"))
        self.in_7_data.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Total Vendido por Ano"))
        self.in_8_data_1.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.label_15.setText(_translate("MainWindow", "Selecione o período:"))
        self.label_17.setText(_translate("MainWindow", "até"))
        self.in_8_data_2.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.lb_titulo_2.setText(_translate("MainWindow", "Simulação - Alteração da Tabela Subcategoria"))
        self.lb_sim_a_2.setText(_translate("MainWindow", "ID Categoria"))
        self.lb_sim_3.setText(_translate("MainWindow", "ID Subcategoria"))
        self.S2_alterar.setText(_translate("MainWindow", "Alterar"))
        self.lb_titulo_3.setText(_translate("MainWindow", "Simulação - Alteração da Tabela Vendas"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Incluir o Frete Mínimo"))
        self.lb_51.setText(_translate("MainWindow", "Frete Mínimo: (999,99)"))
        self.S3_alterar_1.setText(_translate("MainWindow", "Alterar"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Dar Desconto em um Período"))
        self.lb_53.setText(_translate("MainWindow", "Data Inicial:"))
        self.S3_alterar_2.setText(_translate("MainWindow", "Alterar"))
        self.lb_54.setText(_translate("MainWindow", "Data Final:"))
        self.lb_55.setText(_translate("MainWindow", "Desconto:   [0, 1]"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Dar Desconto em um Período em vendas com Valor Total Mínimo"))
        self.lb_56.setText(_translate("MainWindow", "Data Inicial:"))
        self.S3_alterar_3.setText(_translate("MainWindow", "Alterar"))
        self.lb_57.setText(_translate("MainWindow", "Data Final:"))
        self.lb_58.setText(_translate("MainWindow", "Desconto:   [0, 1]"))
        self.lb_59.setText(_translate("MainWindow", "Valor Mínimo da venda:"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Dar Desconto em Itens com mais de uma unidade na mesma venda"))
        self.S3_alterar_5.setText(_translate("MainWindow", "Alterar"))
        self.lb_64.setText(_translate("MainWindow", "Desconto:  [0, 1]"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Dar Desconto em Vendas de um País"))
        self.S3_alterar__4.setText(_translate("MainWindow", "Alterar"))
        self.lb_65.setText(_translate("MainWindow", "Desconto:  [0, 1]"))
        self.lb_66.setText(_translate("MainWindow", "Sigla do País:"))
        self.menuUser.setTitle(_translate("MainWindow", "Usuário"))
        self.menuSim.setTitle(_translate("MainWindow", "Simulações"))
        self.menuRel.setTitle(_translate("MainWindow", "Relatórios"))
        self.menuOverview.setTitle(_translate("MainWindow", "Overview"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionR1.setText(_translate("MainWindow", "R1 - Clientes com cartões vencidos"))
        self.actionR2.setText(_translate("MainWindow", "R2 - Histórico de departamento de funcionários"))
        self.actionR3.setText(_translate("MainWindow", "R3 - Dados de frete"))
        self.actionR4.setText(_translate("MainWindow", "R4 - Informações das vendas anuais"))
        self.actionR5.setText(_translate("MainWindow", "R5 - Top 15 produtos vendidos no semestre"))
        self.actionR6.setText(_translate("MainWindow", "R6 - Produtos de vendas casadas"))
        self.actionR7.setText(_translate("MainWindow", "R7 - Vendas por país"))
        self.actionS1.setText(_translate("MainWindow", "S1 - Produtos"))
        self.actionS2.setText(_translate("MainWindow", "S2 - Subcategoria"))
        self.actionS3.setText(_translate("MainWindow", "S3 - Venda"))
        self.actionCr_ditos.setText(_translate("MainWindow", "Créditos"))
        self.actionOverview.setText(_translate("MainWindow", "Overview"))
        self.actionVisualizar.setText(_translate("MainWindow", "Visualizar"))

class MyTableModel(QAbstractTableModel):
    def __init__(self, datain, headerdata, parent=None):
        """
        Args:
            datain: a list of lists\n
            headerdata: a list of strings
        """
        QAbstractTableModel.__init__(self, None)
        self.arraydata = datain
        self.headerdata = headerdata

    def rowCount(self, parent):
        return len(self.arraydata)

    def columnCount(self, parent):
        if len(self.arraydata) > 0: 
            return len(self.arraydata[0]) 
        return 0

    def data(self, index, role):
        if not index.isValid():
            return QVariant()
        elif role != Qt.DisplayRole:
            return QVariant()
        return QVariant(self.arraydata[index.row()][index.column()])

    def setData(self, index, value, role):
        pass         # not sure what to put here

    def headerData(self, col, orientation, role):
        if orientation == Qt.Horizontal and role == Qt.DisplayRole:
            return QVariant(self.headerdata[col])
        return QVariant()

    def sort(self, Ncol, order):
        """
        Sort table by given column number.
        """
        self.emit(SIGNAL("layoutAboutToBeChanged()"))
        self.arraydata = sorted(self.arraydata, key=operator.itemgetter(Ncol))       
        if order == Qt.DescendingOrder:
            self.arraydata.reverse()
        self.emit(SIGNAL("layoutChanged()"))

